#!/bin/bash

make distclean

echo autoclean: cleaning root
rm -rf aclocal.m4 \
       autom4te.cache \
       autoscan.log \
       config.guess \
       bios.pc \
       config.h \
       config.h.in~ \
       config.h.in \
       config.sub \
       config.status \
       configure \
       depcomp \
       install-sh \
       ltmain.sh \
       missing \
       Makefile \
       stamp-h1 \
       libtool \
       config.log \
       `find . -name Makefile.in`

echo autoclean: cleaning m4
cd m4 && rm -rf \
       libtool.m4 \
       lt~obsolete.m4 \
       ltoptions.m4 \
       ltsugar.m4 \
       ltversion.m4
cd ..

echo autoclean: cleaning doc
cd doc && rm -rf \
       Doxyfile
cd ..
